spin_manifest_version = 2

[application]
name = "api-two"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "api-two"

[component.api-two]
source = "main.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = ["redis://localhost"]

[component.api-two.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
