spin_manifest_version = 2

[application]
name = "api-four"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "api-four"

[component.api-four]
source = "target/wasm32-wasi/release/api_four.wasm"
allowed_outbound_hosts = []
ai_models = ["llama2-chat"]

[component.api-four.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
