spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""
name = "api-three"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "api-three"

[component.api-three]
source = "target/api-three.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.api-three.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
